#!/bin/bash
# Research a company and generate intelligence briefing
# Usage: ./research-company.sh "Company Name"

set -e

COMPANY="$1"
if [ -z "$COMPANY" ]; then
    echo "Usage: $0 \"Company Name\""
    exit 1
fi

# Sanitize company name for filename
SAFE_NAME=$(echo "$COMPANY" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
OUTPUT_DIR="$(dirname "$0")/../output"
BRIEF_FILE="$OUTPUT_DIR/${SAFE_NAME}-brief.md"
RAW_FILE="$OUTPUT_DIR/${SAFE_NAME}-raw.json"

mkdir -p "$OUTPUT_DIR"

echo "🔍 Researching: $COMPANY"
echo "📝 Output: $BRIEF_FILE"
echo ""

# Create initial structure
cat > "$RAW_FILE" <<EOF
{
  "company": "$COMPANY",
  "researched_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "searches": {},
  "analysis": {}
}
EOF

# Note: This script is a placeholder for the actual research workflow
# The real research is done through Flux using web_search and web_fetch
# This script provides the structure and can be enhanced with API calls

cat > "$BRIEF_FILE" <<EOF
# Company Brief: $COMPANY

**Research Date:** $(date -u +%Y-%m-%d)
**Researcher:** Flux (IIoT Solutions AI)

---

## 🏢 Company Overview

**Status:** Research in progress

**Industry:** TBD
**Location:** TBD
**Size:** TBD
**Founded:** TBD
**Website:** TBD

## 🔧 Digital Maturity Assessment

**Current Tech Stack:**
- TBD

**Automation Level:**
- TBD

**Industry 4.0 Readiness:**
- TBD

## 🎯 Identified Opportunities

### Potential Pain Points
- TBD

### IIoT Solutions Fit
- TBD

### Recommended Services
- [ ] SIRI Assessment
- [ ] MES Implementation
- [ ] SCADA Systems
- [ ] System Integration
- [ ] Digital Transformation Consulting

## 👤 Key Decision Makers

| Name | Title | Background | Contact |
|------|-------|------------|---------|
| TBD | TBD | TBD | TBD |

## 📋 Recommended Approach

**Initial Contact Strategy:**
TBD

**Value Proposition:**
TBD

**Talking Points:**
- TBD

## 📊 SIRI Context (Saudi Companies)

**SIRI Level:** TBD
**Industry 4.0 Initiatives:** TBD
**Government Support Programs:** TBD

---

## 🔗 Research Sources

- Web search results
- Company website
- Industry reports
- News articles

## 📝 Next Steps

- [ ] Validate research findings
- [ ] Identify direct contact
- [ ] Add to HubSpot CRM
- [ ] Prepare initial outreach
- [ ] Schedule follow-up research

---

*This briefing is generated by Flux and requires human validation before use in client communications.*
EOF

echo "✅ Initial brief created: $BRIEF_FILE"
echo ""
echo "🤖 Note: This is a template. Use Flux directly for detailed research:"
echo "   Ask Flux: \"Research [Company Name] for business development\""
echo ""
