#!/usr/bin/env node

const fs = require('fs');
const { google } = require('googleapis');

// Read OAuth credentials
const credentials = JSON.parse(fs.readFileSync('../../config/google-oauth-credentials.json'));
const token = JSON.parse(fs.readFileSync('../../config/google-token.json'));

const { client_secret, client_id, redirect_uris } = credentials.installed || credentials.web;
const oAuth2Client = new google.auth.OAuth2(client_id, client_secret, redirect_uris[0]);
oAuth2Client.setCredentials(token);

const gmail = google.gmail({ version: 'v1', auth: oAuth2Client });

// Read the summary
const summary = fs.readFileSync('./meeting-summary.md', 'utf8');

// Convert markdown to HTML (simple conversion)
function mdToHtml(md) {
  let html = md
    // Headers
    .replace(/^### (.*$)/gim, '<h3 style="color: #1a73e8; margin-top: 24px; margin-bottom: 12px;">$1</h3>')
    .replace(/^## (.*$)/gim, '<h2 style="color: #202124; margin-top: 32px; margin-bottom: 16px; border-bottom: 2px solid #e8eaed; padding-bottom: 8px;">$1</h2>')
    .replace(/^# (.*$)/gim, '<h1 style="color: #202124; margin-bottom: 24px;">$1</h1>')
    // Bold
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    // Code blocks
    .replace(/```(.*?)```/gs, '<pre style="background: #f8f9fa; padding: 16px; border-radius: 4px; overflow-x: auto;"><code>$1</code></pre>')
    // Inline code
    .replace(/`(.*?)`/g, '<code style="background: #f8f9fa; padding: 2px 6px; border-radius: 3px; font-family: monospace;">$1</code>')
    // Lists
    .replace(/^\- (.*$)/gim, '<li style="margin-bottom: 8px;">$1</li>')
    .replace(/^\d+\. (.*$)/gim, '<li style="margin-bottom: 8px;">$1</li>')
    // Tables
    .replace(/\|/g, '')
    // Blockquotes
    .replace(/^&gt; (.*$)/gim, '<blockquote style="border-left: 4px solid #1a73e8; padding-left: 16px; margin: 16px 0; color: #5f6368; font-style: italic;">$1</blockquote>')
    // Horizontal rules
    .replace(/^---$/gim, '<hr style="border: none; border-top: 1px solid #e8eaed; margin: 24px 0;">')
    // Line breaks
    .replace(/\n\n/g, '</p><p style="margin: 12px 0;">')
    .replace(/\n/g, '<br>');

  // Wrap lists
  html = html.replace(/(<li.*?<\/li>(\s*<li.*?<\/li>)*)/g, '<ul style="margin: 12px 0; padding-left: 24px;">$1</ul>');
  
  return `<p style="margin: 12px 0;">${html}</p>`;
}

const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Team Meeting Summary - Feb 4, 2026</title>
</head>
<body style="font-family: 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #202124; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #ffffff;">
  
  <div style="background: linear-gradient(135deg, #1a73e8 0%, #4285f4 100%); color: white; padding: 32px; border-radius: 8px; margin-bottom: 32px;">
    <h1 style="margin: 0 0 8px 0; font-size: 28px;">📋 Team Meeting Summary</h1>
    <p style="margin: 0; opacity: 0.9; font-size: 16px;">February 4, 2026 • 70 minutes • Recorded & Transcribed</p>
  </div>

  <div style="background: #fff; padding: 24px; border-radius: 8px;">
    ${mdToHtml(summary)}
  </div>

  <div style="margin-top: 32px; padding: 20px; background: #f8f9fa; border-radius: 8px; border-left: 4px solid #1a73e8;">
    <p style="margin: 0; font-size: 14px; color: #5f6368;">
      <strong>📎 Attachments Available:</strong><br>
      • Full transcript (70 minutes)<br>
      • Meeting recording (94MB MP4)<br>
      • Meeting summary (MD format)<br><br>
      <em>Stored in: workspace/meetings/2026-02-04/</em>
    </p>
  </div>

  <div style="margin-top: 24px; text-align: center; padding: 20px; color: #5f6368; font-size: 12px; border-top: 1px solid #e8eaed;">
    <p style="margin: 0;">This summary was automatically generated by Flux 🔄</p>
    <p style="margin: 4px 0 0 0;">IIoT Solutions • Jeddah, Saudi Arabia</p>
  </div>

</body>
</html>
`;

// Create email
const email = [
  'Content-Type: text/html; charset=utf-8',
  'MIME-Version: 1.0',
  'To: ayman@iiotsolutions.sa, aadil@iiotsolutions.sa, hamad@iiotsolutions.sa',
  'From: coding@iiotsolutions.sa',
  'Subject: Team Meeting Summary - Feb 4, 2026 (Voltonic, Pricing, POC Urgency)',
  '',
  htmlBody
].join('\n');

const encodedEmail = Buffer.from(email)
  .toString('base64')
  .replace(/\+/g, '-')
  .replace(/\//g, '_')
  .replace(/=+$/, '');

async function sendEmail() {
  try {
    const result = await gmail.users.messages.send({
      userId: 'me',
      requestBody: {
        raw: encodedEmail
      }
    });
    
    console.log('✅ Email sent successfully!');
    console.log('Message ID:', result.data.id);
  } catch (error) {
    console.error('❌ Error sending email:', error.message);
    if (error.response) {
      console.error('Response:', error.response.data);
    }
    process.exit(1);
  }
}

sendEmail();
